### ISSUE TITLE
Circular references in typing

### ISSUE THREAD

**Issue by seriema** [xobotyi/cnbuilder#253]
We use [dts-bundle-generator](https://github.com/timocov/dts-bundle-generator) and running `dts-bundle-generator --out-file dist/bundle.d.ts src/main.ts` results in errors around circular dependencies in the types:

```
../../node_modules/cnbuilder/dist/types.d.ts(1,21): error TS2456: Type alias 'ClassValue' circularly references itself.
19:07:34
../../node_modules/cnbuilder/dist/types.d.ts(2,21): error TS2456: Type alias 'ClassListArray' circularly references itself.
```

**Comment by xobotyi** [comment]
That one is unfixable.
Since `cnb` supports any level of nesting (array-wise) there is no other way to tipe it without circular types.

**Comment by xobotyi** [comment]
Weel it is actually fixable in case i'll change the behaviour and make only one level of array nesting possible.
Because i've made the library to be a drop-in replacement of classnames, which supports any level of array nesting, i've left that behavior, but if judge sanity-wise - there is no sence: i've never had nested array-classlist for last 3 years im using classnames building libraries.

**Comment by seriema** [comment]
Looks like typing circular references came in TS 3.7

https://github.com/microsoft/TypeScript/pull/33050

Some other ways

https://stackoverflow.com/questions/36966444/how-to-create-a-circularly-referenced-type-in-typescript

**Comment by seriema** [comment]
Silly me, I should have checked `dts-bundle-generator` first. It was outdated and using a lower version of TypeScript (3.6.2, that didn't have circular reference support). Upgrading fixed the issue.
